In [1]:
import pandas as pd
import pickle
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import GridSearchCV
import numpy as np


ImportError: cannot import name 'euler_gamma'

## Import the fully created data file

In [2]:
fullData = pd.read_csv("../data/interim/" + "CrimesMergedWithWeather.csv")

In [3]:
fullData.head()

Date  Zipcode  Description  MeanAppTemp  PrecipIntensity  PrecipProb
0  2011-01-01    60607           15        8.405             0.07        0.07
1  2011-01-01    60608           29        8.405             0.07        0.07
2  2011-01-01    60609           39        8.405             0.07        0.07
3  2011-01-01    60612           86        8.405             0.07        0.07
4  2011-01-01    60614           43        8.405             0.07        0.07

In [10]:
fullData.rename(columns={"Description":"Crime_Count"}, inplace = True)

In [12]:
Y = fullData["Crime_Count"]
X = fullData[["Zipcode","MeanAppTemp","PrecipIntensity","PrecipProb"]]

## Create a 500 tree rf model template

In [36]:
rf = RandomForestRegressor(random_state=0, n_estimators = 500)

In [37]:
fitted = rf.fit(X, Y)

In [38]:
fitted.feature_importances_

array([ 0.66720787,  0.26921729,  0.03182603,  0.03174881])

In [30]:
Y.iloc[1]

29

In [40]:
fitted.predict(X.iloc[1].values.reshape(1,-1))

array([ 25.934])

### Parameters to tune

In [41]:
param_grid = {
                 'n_estimators': [500, 800],
                 'max_depth': [2, 5, 10]
             }

In [42]:
bestModelRF = GridSearchCV(rf, cv=5, param_grid = param_grid)

In [43]:
bestModelRF.fit(X,Y)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=500, n_jobs=1, oob_score=False, random_state=0,
           verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [500, 800], 'max_depth': [2, 5, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [1]:
bestModelRF.best_estimator_

NameError: name 'bestModelRF' is not defined

### Parameters to fine tune

In [46]:
param_grid2 = {
                'n_estimators': [650, 800, 950],
                 'max_depth': [8, 10, 12]
              }


In [47]:
bestModelRF2 = GridSearchCV(rf, cv=5, param_grid = param_grid2 )

In [49]:
bestModelRF2.fit(X,Y)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=500, n_jobs=1, oob_score=False, random_state=0,
           verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [650, 800, 950], 'max_depth': [8, 10, 12]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [50]:
bestModelRF2.best_params_

{'max_depth': 10, 'n_estimators': 950}

### Final fine tuning

In [51]:
param_grid3 = {
                'n_estimators': [850, 950, 1050],
                 'max_depth': [9, 10, 11]
              }

In [52]:
bestModelRF3 = GridSearchCV(rf, cv=5, param_grid = param_grid3 )

In [53]:
bestModelRF3.fit(X,Y)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=500, n_jobs=1, oob_score=False, random_state=0,
           verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [850, 950, 1050], 'max_depth': [9, 10, 11]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [54]:
bestModelRF3.best_params_

{'max_depth': 10, 'n_estimators': 950}

In [55]:
bestModelRF3.predict(X.iloc[1].values.reshape(1,-1))

array([ 18.44083339])

### Save final model as pkl file

In [56]:
with open('RandomForestModel.pkl', 'wb') as f:
    pickle.dump(bestModelRF3, f)